### ISSUE TITLE
Manager API - Create menu from file

### ISSUE THREAD

**Issue by averma1** [averma1/RockstarRestaurant#18]

**Comment by pmank64** [comment]
Done when menu items objects exist for all items in the file

**Comment by JohnHunter809** [comment]
3 hrs: made basic tests. Working on getting them to pass. Lots of impediments for this one

**Comment by JohnHunter809** [comment]
3 hrs: gettings the tests to finally pass.

**Comment by pmank64** [comment]
4/10
2hrs: worked with John to write implementation
