### ISSUE TITLE
Manager API - Edit stock, Remove based on meal

### ISSUE THREAD

**Issue by averma1** [averma1/RockstarRestaurant#22]

**Comment by pmank64** [comment]
Done when it is verified that the appropriate stock and quantity of stock has been subtracted when a meal is ordered

**Comment by CryptoGraphicDragon** [comment]
30 min- implemented function and added javadocs, still needs tests (in integrationTestsBranch)

**Comment by CryptoGraphicDragon** [comment]
30 min- make sure every take order function removes from stock

**Comment by CryptoGraphicDragon** [comment]
1 hr- rewrote implementation, added a new function, and wrote tests for both
