### ISSUE TITLE
Manager API - Edit stock, add based on item

### ISSUE THREAD

**Issue by averma1** [averma1/RockstarRestaurant#25]

**Comment by JohnHunter809** [comment]
3/18 in class
45 min: Setting up the branches and project

**Comment by JohnHunter809** [comment]
3/18
30 min: Setting up the Ingredient class so its ready for the stock class

**Comment by pmank64** [comment]
3/19
1.5hr: Writing the stock class and tests for the stock class

**Comment by JohnHunter809** [comment]
3/19
30 min: writing tests for ingredient class, and writing code to make them pass
15 min: working with peter to get pull request going

**Comment by pmank64** [comment]
3/19
30min: working with John to create pull request

**Comment by JohnHunter809** [comment]
3/21
45 min: added skeleton managerAPI and worked on its tests

**Comment by pmank64** [comment]
3/21
1hr: edit the different parts of a stock item

**Comment by JohnHunter809** [comment]
40 min: merging with master
