### ISSUE TITLE
Host API - View table status

### ISSUE THREAD

**Issue by averma1** [averma1/RockstarRestaurant#33]
when done: prints info on table (number, size, if anyone is there or not, how many people are sitting there)

**Comment by EMurtaghh** [comment]
viewTableTest- 15min

**Comment by EMurtaghh** [comment]
Didnt like initial implemention of viewTableTest. Needs to be quickly discussed tomorrow on what the function should even look like.

**Comment by averma1** [comment]
viewTableTest - maybe 30-45 minutes ?? completed

**Comment by averma1** [comment]
printTableDataTest - 30 minutes
