### ISSUE TITLE
Host API - Manage waitlist for tables

### ISSUE THREAD

**Issue by averma1** [averma1/RockstarRestaurant#37]

**Comment by pmank64** [comment]
Done when a class that keeps track of a sequential order of customers exists

**Comment by CryptoGraphicDragon** [comment]
1 hr- set up and tests written

**Comment by CryptoGraphicDragon** [comment]
30 min- waitlist basic implementation

**Comment by CryptoGraphicDragon** [comment]
30 min- add better tests, change removeFromWaitlist, add javadocs
