### ISSUE TITLE
Host API - Create tables

### ISSUE THREAD

**Issue by averma1** [averma1/RockstarRestaurant#38]
when done: Able to create a table based on size and table number

**Comment by EMurtaghh** [comment]
Table Class- 30min

**Comment by CryptoGraphicDragon** [comment]
3/18  (1 hour)  Everyone spent the class managing the branches and ensuring everything worked

**Comment by averma1** [comment]
TableTests - 30 min

**Comment by averma1** [comment]
TableTests - 30 min (completed)

**Comment by JohnHunter809** [comment]
10 min: code review for the table and host api branch
