### ISSUE TITLE
Host API- Split table

### ISSUE THREAD

**Issue by CryptoGraphicDragon** [averma1/RockstarRestaurant#45]
when done: takes a combined table and splits them into two

**Comment by EMurtaghh** [comment]
splitTableTest 18min

**Comment by CryptoGraphicDragon** [comment]
Created multitable so as to keep track of the tables used to create a table to split, don't know if I did it right, or where to go from here. 30 min

**Comment by EMurtaghh** [comment]
splitTableTest- 30min
