### ISSUE TITLE
Waiter API - Take orders from a table

### ISSUE THREAD

**Issue by pmank64** [averma1/RockstarRestaurant#5]

**Comment by pmank64** [comment]
Done when correct order items exist for a given table that has ordered

**Comment by CryptoGraphicDragon** [comment]
1 hr- setting up order class and interaction with table

**Comment by CryptoGraphicDragon** [comment]
30 min- made order tests

**Comment by CryptoGraphicDragon** [comment]
30 min- made new table tests to interact with orders

**Comment by EMurtaghh** [comment]
takeOrderTest: 31min

**Comment by CryptoGraphicDragon** [comment]
15 min- order implementation

**Comment by averma1** [comment]
1 hr - setting up class and interaction with table

**Comment by averma1** [comment]
1.5 hours - table implementation

**Comment by CryptoGraphicDragon** [comment]
30 min- merging menu item and fixing errors

**Comment by EMurtaghh** [comment]
15min - fixing takeOrderTest

**Comment by CryptoGraphicDragon** [comment]
1 hr- reworking the hostAPI, waiterAPI and restaurant so everyone can access all the tables and thus create an order
