### ISSUE TITLE
Manager UI

### ISSUE THREAD

**Issue by CryptoGraphicDragon** [averma1/RockstarRestaurant#53]

**Comment by averma1** [comment]
done when: after logging in, a manager can access all the functionality through the UI

**Comment by averma1** [comment]
30 min - implementation (basic skeleton and functions)

**Comment by averma1** [comment]
1 hour - pair programming with Emma

**Comment by EMurtaghh** [comment]
1hr- worked w Anika

**Comment by averma1** [comment]
1 hour - initial implementation of manager that i ended up scrapping on 4/23
