### ISSUE TITLE
Bartender- Place order

### ISSUE THREAD

**Issue by CryptoGraphicDragon** [averma1/RockstarRestaurant#59]

**Comment by averma1** [comment]
30 min - setting everything up and planning how bartender will work

**Comment by CryptoGraphicDragon** [comment]
30 min- update functions and talk about implementation

**Comment by EMurtaghh** [comment]
30min setting up bartenderBranch
30min talking about bartender and how the implementation is going to work

**Comment by CryptoGraphicDragon** [comment]
30 min- test formatting update

**Comment by EMurtaghh** [comment]
26 minutes- test
