### ISSUE TITLE
Waiter API- View Order

### ISSUE THREAD

**Issue by EMurtaghh** [averma1/RockstarRestaurant#64]
done when: can view a persons order from a table

**Comment by EMurtaghh** [comment]
viewOrderTest (initial version): 07min

**Comment by EMurtaghh** [comment]
4 minutes to fix viewOrderTest

**Comment by CryptoGraphicDragon** [comment]
30 min- implement view order

**Comment by CryptoGraphicDragon** [comment]
5 min- fixing view order after realizing it needs takeOrder in order to function
