### ISSUE TITLE
Login Verification System

### ISSUE THREAD

**Issue by EMurtaghh** [averma1/RockstarRestaurant#78]
Done when:
Type in a 4 digit code that logs you into your corresponding role

**Comment by CryptoGraphicDragon** [comment]
30 min- set up

**Comment by CryptoGraphicDragon** [comment]
30 min- implementation of enum and check if  valid pin

**Comment by CryptoGraphicDragon** [comment]
1.5 hours- writing tests and making implementation that passed them
