### ISSUE TITLE
Figure out how to create the GUI

### ISSUE THREAD

**Issue by pmank64** [averma1/RockstarRestaurant#79]

**Comment by JohnHunter809** [comment]
Done When: Every member of the team has some understanding of how to use JFrame (or whatever GUI tool we use)

**Comment by EMurtaghh** [comment]
1hr 15min- experimenting with JFrame/JOptionPane/JPanel in thursday lab class

**Comment by averma1** [comment]
1 hour 15 min - experimenting with GUI in lab

**Comment by JohnHunter809** [comment]
1 hr: discussing in class

**Comment by pmank64** [comment]
3hrs: worked to figure out how to integrate everything together
