### ISSUE TITLE
Login Pin UI

### ISSUE THREAD

**Issue by pmank64** [averma1/RockstarRestaurant#80]

**Comment by JohnHunter809** [comment]
Done when:
-you can log into your role based on a unique 4 digit code given to every employee
-manager can create pins for new employees
-load in pins from file?

**Comment by EMurtaghh** [comment]
1hr 35min- getting basic UI design functional

**Comment by averma1** [comment]
1 hour - getting initial skeleton functional

**Comment by EMurtaghh** [comment]
1hr 6min- working on implementation

**Comment by averma1** [comment]
30 min - implementation

**Comment by averma1** [comment]
1 hour - pair programming w John on implementation

**Comment by JohnHunter809** [comment]
1 hour - working with anika

**Comment by JohnHunter809** [comment]
1 hr: discussing with toby, emma and peter about how this should be done

**Comment by JohnHunter809** [comment]
2.5 hrs: Pair programming with peter to rework the structure of the GUI

**Comment by pmank64** [comment]
2 hrs: discussing with Toby, John and Emma about how to structure the GUI, and discussing in class

**Comment by pmank64** [comment]
2.5 hrs: Pair programming with John to rework the structure of the GUI

**Comment by JohnHunter809** [comment]
30 min: discussing with toby

**Comment by averma1** [comment]
10 min - pair programming w Emma for update pin string

**Comment by EMurtaghh** [comment]
10min- fixing login pin to update the screen w Anika.

**Comment by EMurtaghh** [comment]
4hr 9min, asking toby for help, working w John and Peter, working on my own from past week.
